/*
    VEHICLE_TYPE = What type the vehicle is.
        types : ['AA', 'APC', 'ARMEDCAR', 'ARTILLERY', 'BOAT', 'HELI', 'PLANE', 'STATICAA', 'STATICAT', 'STATICMG', 'STATICMORTAR', 'TANK', 'UAV', 'UNARMEDCAR']

    VEHICLE_CONDITION = Condition to show.
        VEHICLE_CONDITION_X : VEHICLE_CONDITION + VEHICLE_TYPE

    VEHICLE_CONDITION_X can also be replaced with a string to add your own condition.

    ITEM(CLASSNAME, PRICE, VEHICLE_TYPE, VEHICLE_CONDITION_X);
*/

class arg_vehicles_arg : vehicles_base
{
    ITEM(Unimog_small, 400, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(Unimog416_big, 500, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(acfaa_m1083a1p2_green, 750, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(acfaa_m1025a2, 600, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(acfaa_m1043, 700, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(acfaa_m998_4door, 800, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(acfaa_m998, 800, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(acfaa_gmv, 1000, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);

    ITEM(acfaa_m1025a2_m240, 3000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(acfaa_m1025a2_m2, 5000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(acfaa_m1025a2_mk19, 8000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(acfaa_m1025a2_tow, 12500, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(acfaa_m1043_m240, 4000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(acfaa_m1043_m2, 6500, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(acfaa_m1043_mk19, 1000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(acfaa_m1045_tow, 15000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(acfaa_gmv_m2, 8000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(acfaa_gmv_m134, 12500, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);

    ITEM(acfaa_m113_m2, 12000, APC, VEHICLE_CONDITION_APC);
    ITEM(acfaa_AAVP7A1, 20000, APC, VEHICLE_CONDITION_APC);
    ITEM(CLV_VCTP, 15000, APC, VEHICLE_CONDITION_APC);
    ITEM(CLV_VCTP2IP, 175000, APC, VEHICLE_CONDITION_APC);
    ITEM(acfaa_PandurII_EA, 25000, APC, VEHICLE_CONDITION_APC);

    ITEM(clv_Aml20, 15000, TANK, VEHICLE_CONDITION_TANK);
    ITEM(clv_Aml90, 20000, TANK, VEHICLE_CONDITION_TANK);
    ITEM(clv_AmlHS30, 17500, TANK, VEHICLE_CONDITION_TANK);
    ITEM(clv_Amx13, 25000, TANK, VEHICLE_CONDITION_TANK);
    ITEM(clv_Kurassier, 30000, TANK, VEHICLE_CONDITION_TANK);
    ITEM(clv_TAM, 40000, TANK, VEHICLE_CONDITION_TANK);
    ITEM(clv_TAM2C, 50000, TANK, VEHICLE_CONDITION_TANK);

    ITEM(clv_Dragon, 20000, AA, VEHICLE_CONDITION_AA);

    ITEM(acfaa_at6b, 15000, PLANE, VEHICLE_CONDITION_PLANE);

    ITEM(acfaa_h500d, 10000, HELI, VEHICLE_CONDITION_HELI);
    ITEM(acfaa_heli_UH1N_unarmed, 12500, HELI, VEHICLE_CONDITION_HELI);
    ITEM(acfaa_heli_bell412, 15000, HELI, VEHICLE_CONDITION_HELI);
    ITEM(ACFAA_ARG_UH1H_M60, 17500, HELI, VEHICLE_CONDITION_HELI);
    ITEM(ACFAA_EA_CH47F_M134, 25000, HELI, VEHICLE_CONDITION_HELI);
    ITEM(acfaa_ab206, 15000, HELI, VEHICLE_CONDITION_HELI);
    ITEM(acfaa_h500d_armed, 15000, HELI, VEHICLE_CONDITION_HELI);
    ITEM(ACFAA_ARG_UH1H_AR, 13000, HELI, VEHICLE_CONDITION_HELI);
    ITEM(acfaa_heli_UH1N_m240, 15000, HELI, VEHICLE_CONDITION_HELI);

    ITEM(CLV_OERLIKON, 750, STATICAA, VEHICLE_CONDITION_STATICAA);

    ITEM(CLV_OMM56, 1500, ARTILLERY, VEHICLE_CONDITION_ARTILLERY);

};