/*
    VEHICLE_TYPE = What type the vehicle is.
        types : ['AA', 'APC', 'ARMEDCAR', 'ARTILLERY', 'BOAT', 'HELI', 'PLANE', 'STATICAA', 'STATICAT', 'STATICMG', 'STATICMORTAR', 'TANK', 'UAV', 'UNARMEDCAR']

    VEHICLE_CONDITION = Condition to show.
        VEHICLE_CONDITION_X : VEHICLE_CONDITION + VEHICLE_TYPE

    VEHICLE_CONDITION_X can also be replaced with a string to add your own condition.

    ITEM(CLASSNAME, PRICE, VEHICLE_TYPE, VEHICLE_CONDITION_X);
*/

class FAN_vehicles_CUP : vehicles_base
{
    ITEM(B_Quadbike_01_F, 100, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);

    ITEM(CUP_B_Kamaz_CDF, 400, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(CUP_O_Ural_SLA, 500, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);

    ITEM(CUP_I_M151_SYND, 250, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(CUP_B_nM1025_Unarmed_USMC_WDL, 1000, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(CUP_O_Tigr_233014_SLA, 1000, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);

    ITEM(CUP_I_M151_M2_SYND, 1500, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_O_Tigr_233014_PK_SLA, 3000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_B_HMMWV_Crows_M2_NATO_T, 4000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_O_Tigr_M_233114_GREEN_KORD_RU, 5000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_B_RG31_M2_OD_GC_USA, 5500, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_B_RG31_Mk19_OD_USA, 7500, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_B_nM1025_SOV_M2_NATO_T, 5000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_B_nM1025_SOV_Mk19_NATO_T, 8000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_B_RG31E_M2_OD_USA, 7000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);

    ITEM(CUP_O_BRDM2_HQ_SLA, 8000, APC, VEHICLE_CONDITION_APC);
    ITEM(CUP_O_BRDM2_SLA, 10000, APC, VEHICLE_CONDITION_APC);
    ITEM(CUP_O_BRDM2_ATGM_SLA, 14000, APC, VEHICLE_CONDITION_APC);
    ITEM(CUP_O_BTR60_SLA, 10000, APC, VEHICLE_CONDITION_APC);
    ITEM(CUP_O_BTR80_SLA, 11000, APC, VEHICLE_CONDITION_APC);
    ITEM(CUP_O_BTR80A_SLA, 15000, APC, VEHICLE_CONDITION_APC);
    ITEM(CUP_O_MTLB_pk_SLA, 17500, APC, VEHICLE_CONDITION_APC);
    ITEM(CUP_O_BMP2_SLA, 22500, APC, VEHICLE_CONDITION_APC);
    ITEM(CUP_B_M113A1_HQ_olive_USA, 20000, APC, VEHICLE_CONDITION_APC);
    ITEM(CUP_B_M113A1_olive_USA, 22500, APC, VEHICLE_CONDITION_APC);

    ITEM(CUP_O_Ural_ZU23_SLA, 6000, AA, VEHICLE_CONDITION_AA);
    ITEM(CUP_O_BMP2_ZU_TKA, 1000, AA, VEHICLE_CONDITION_AA);
    ITEM(CUP_B_M163_Vulcan_USA, 17000, AA, VEHICLE_CONDITION_AA);
    ITEM(CUP_O_ZSU23_Afghan_SLA, 17000, AA, VEHICLE_CONDITION_AA);

    ITEM(CUP_I_T34_NAPA, 25000, TANK, VEHICLE_CONDITION_TANK);
    ITEM(CUP_O_T55_SLA, 30000, TANK, VEHICLE_CONDITION_TANK);
    ITEM(CUP_B_M60A3_USMC, 40000, TANK, VEHICLE_CONDITION_TANK);
    ITEM(CUP_O_BMP3_CSAT_T, 40000, TANK, VEHICLE_CONDITION_TANK);

    ITEM(CUP_O_BM21_SLA, 30000, ARTILLERY, VEHICLE_CONDITION_ARTILLERY);

    ITEM(I_Heli_light_03_unarmed_F, 15000, HELI, VEHICLE_CONDITION_HELI);
    ITEM(B_Heli_Light_01_F, 17500, HELI, VEHICLE_CONDITION_HELI);
    ITEM(B_Heli_Light_01_dynamicLoadout_F, 20500, HELI, VEHICLE_CONDITION_HELI);
    ITEM(CUP_I_Wildcat_Green_AAF, 17500, HELI, VEHICLE_CONDITION_HELI);
    ITEM(CUP_O_UH1H_SLA, 15000, HELI, VEHICLE_CONDITION_HELI);
    ITEM(CUP_O_UH1H_slick_SLA, 15000, HELI, VEHICLE_CONDITION_HELI);
    ITEM(CUP_O_UH1H_armed_SLA, 25000, HELI, VEHICLE_CONDITION_HELI);
    ITEM(CUP_O_UH1H_gunship_SLA, 30000, HELI, VEHICLE_CONDITION_HELI);

    ITEM(CUP_O_LCVP_SLA, 15000, BOAT, VEHICLE_CONDITION_BOAT);

    ITEM(CUP_O_DSHKM_SLA, 2000, STATICMG, VEHICLE_CONDITION_STATICMG);
    ITEM(I_G_HMG_02_F, 2500, STATICMG, VEHICLE_CONDITION_STATICMG);
    ITEM(I_G_HMG_02_high_F, 2500, STATICMG, VEHICLE_CONDITION_STATICMG);
    ITEM(CUP_I_AGS_TK_GUE, 4000, STATICMG, VEHICLE_CONDITION_STATICMG);
    ITEM(CUP_O_KORD_high_RUS_M_Summer, 3000, STATICMG, VEHICLE_CONDITION_STATICMG);

    ITEM(CUP_I_M252_RACS, 7000, STATICMORTAR, VEHICLE_CONDITION_STATICMORTAR);

    ITEM(CUP_I_ZU23_NAPA, 4500, STATICAA, VEHICLE_CONDITION_STATICAA);
    ITEM(CUP_O_Igla_AA_pod_SLA, 7000, STATICAA, VEHICLE_CONDITION_STATICAA);
    ITEM(CUP_B_CUP_Stinger_AA_pod_US, 7000, STATICAA, VEHICLE_CONDITION_STATICAA);

    ITEM(CUP_I_SPG9_NAPA, 5500, STATICAT, VEHICLE_CONDITION_STATICAT);
    ITEM(CUP_O_Kornet_RUS_M_Summer, 7000, STATICAT, VEHICLE_CONDITION_STATICAT);
};