/*
    VEHICLE_TYPE = What type the vehicle is.
        types : ['AA', 'APC', 'ARMEDCAR', 'ARTILLERY', 'BOAT', 'HELI', 'PLANE', 'STATICAA', 'STATICAT', 'STATICMG', 'STATICMORTAR', 'TANK', 'UAV', 'UNARMEDCAR']

    VEHICLE_CONDITION = Condition to show.
        VEHICLE_CONDITION_X : VEHICLE_CONDITION + VEHICLE_TYPE

    VEHICLE_CONDITION_X can also be replaced with a string to add your own condition.

    ITEM(CLASSNAME, PRICE, VEHICLE_TYPE, VEHICLE_CONDITION_X);
*/

class FAN_vehicles_CUP : vehicles_base
{
    ITEM(B_Quadbike_01_F, 100, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);

    ITEM(CUP_C_TT650_CIV, 50, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(CUP_C_Datsun_Plain, 200, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(CUP_C_Golf4_Sport_CR_Civ, 300, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(CUP_O_Hilux_unarmed_CR_CIV, 400, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(CUP_C_SUV_CIV, 400, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(CUP_C_Ural_Open_Civ_03, 500, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(CUP_B_Hilux_armored_unarmed_BLU_G_F, 700, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(CUP_B_nM1025_Unarmed_USMC_WDL, 1000, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(CUP_O_Tigr_233014_SLA, 1000, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);

    ITEM(CUP_B_Hilux_AGS30_BLU_G_F, 3000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_B_Hilux_M2_BLU_G_F, 3000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_B_Hilux_SPG9_BLU_G_F, 4000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_B_Hilux_armored_AGS30_BLU_G_F, 4000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_B_Hilux_armored_M2_BLU_G_F, 4000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_B_Hilux_armored_SPG9_BLU_G_F, 5000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_B_Hilux_armored_metis_BLU_G_F, 8000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_B_Hilux_armored_BTR60_BLU_G_F, 15000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_B_Hilux_armored_BMP1_BLU_G_F, 20000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_O_Tigr_233014_PK_SLA, 3000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_B_nM1025_M2_DF_NATO_T, 4000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_B_nM1025_Mk19_DF_NATO_T, 4000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_B_nM1025_SOV_M2_NATO_T, 6000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_B_nM1025_SOV_Mk19_NATO_T, 6000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);

    ITEM(CUP_O_BRDM2_SLA, 12500, APC, VEHICLE_CONDITION_APC);
    ITEM(CUP_O_BRDM2_HQ_SLA, 10000, APC, VEHICLE_CONDITION_APC);
    ITEM(CUP_O_BRDM2_ATGM_SLA, 15000, APC, VEHICLE_CONDITION_APC);
    ITEM(CUP_O_BTR80_SLA, 20000, APC, VEHICLE_CONDITION_APC);
    ITEM(CUP_O_BTR80A_SLA, 22500, APC, VEHICLE_CONDITION_APC);
    ITEM(CUP_O_MTLB_pk_SLA, 30000, APC, VEHICLE_CONDITION_APC);

    ITEM(CUP_B_Hilux_zu23_BLU_G_F, 5500, AA, VEHICLE_CONDITION_AA);
    ITEM(CUP_B_Hilux_armored_zu23_BLU_G_F, 6000, AA, VEHICLE_CONDITION_AA);
    ITEM(CUP_B_Hilux_armored_igla_BLU_G_F, 7000, AA, VEHICLE_CONDITION_AA);
    ITEM(CUP_O_Ural_ZU23_SLA, 7000, AA, VEHICLE_CONDITION_AA);

    ITEM(CUP_I_T34_NAPA, 40000, TANK, VEHICLE_CONDITION_TANK);
    ITEM(CUP_I_T55_NAPA, 60000, TANK, VEHICLE_CONDITION_TANK);
    ITEM(CUP_B_M60A3_USMC, 80000, TANK, VEHICLE_CONDITION_TANK);

    ITEM(CUP_B_Hilux_podnos_BLU_G_F, 4000, ARTILLERY, VEHICLE_CONDITION_ARTILLERY);
    ITEM(CUP_B_Hilux_armored_podnos_BLU_G_F, 5000, ARTILLERY, VEHICLE_CONDITION_ARTILLERY);
    ITEM(CUP_B_Hilux_armored_MLRS_BLU_G_F, 10000, ARTILLERY, VEHICLE_CONDITION_ARTILLERY);
    ITEM(CUP_B_Hilux_armored_UB32_BLU_G_F, 12500, ARTILLERY, VEHICLE_CONDITION_ARTILLERY);
    ITEM(CUP_O_BM21_SLA, 12500, ARTILLERY, VEHICLE_CONDITION_ARTILLERY);

    ITEM(I_C_Heli_Light_01_civil_F, 15000, HELI, VEHICLE_CONDITION_HELI);
    ITEM(CUP_C_412, 17500, HELI, VEHICLE_CONDITION_HELI);
    ITEM(CUP_B_AH6J_USA, 30000, HELI, VEHICLE_CONDITION_HELI);
    ITEM(CUP_B_AH6M_USA, 30000, HELI, VEHICLE_CONDITION_HELI);
    ITEM(CUP_O_UH1H_SLA, 20000, HELI, VEHICLE_CONDITION_HELI);
    ITEM(CUP_O_UH1H_slick_SLA, 20000, HELI, VEHICLE_CONDITION_HELI);
    ITEM(CUP_O_UH1H_armed_SLA, 25000, HELI, VEHICLE_CONDITION_HELI);
    ITEM(CUP_O_UH1H_gunship_SLA, 30000, HELI, VEHICLE_CONDITION_HELI);

    ITEM(CUP_I_CESSNA_T41_UNARMED_RACS, 20000, PLANE, VEHICLE_CONDITION_PLANE);
    ITEM(CUP_I_CESSNA_T41_ARMED_RACS, 25000, PLANE, VEHICLE_CONDITION_PLANE);

    ITEM(CUP_C_PBX_CIV, 500, BOAT, VEHICLE_CONDITION_BOAT);
    ITEM(CUP_C_Zodiac_CIV, 750, BOAT, VEHICLE_CONDITION_BOAT);
    ITEM(CUP_B_RHIB_USMC, 5000, BOAT, VEHICLE_CONDITION_BOAT);

    ITEM(I_G_HMG_02_F, 3000, STATICMG, VEHICLE_CONDITION_STATICMG);
    ITEM(I_G_HMG_02_high_F, 3000, STATICMG, VEHICLE_CONDITION_STATICMG);
    ITEM(CUP_I_AGS_TK_GUE, 3000, STATICMG, VEHICLE_CONDITION_STATICMG);

    ITEM(CUP_I_2b14_82mm_NAPA, 4000, STATICMORTAR, VEHICLE_CONDITION_STATICMORTAR);
    ITEM(I_G_Mortar_01_F, 5000, STATICMORTAR, VEHICLE_CONDITION_STATICMORTAR);

    ITEM(CUP_I_ZU23_NAPA, 4500, STATICAA, VEHICLE_CONDITION_STATICAA);
    ITEM(CUP_O_Igla_AA_pod_SLA, 6000, STATICAA, VEHICLE_CONDITION_STATICAA);

    ITEM(CUP_I_SPG9_NAPA, 4500, STATICAT, VEHICLE_CONDITION_STATICAT);
    ITEM(CUP_O_Metis_TK, 8000, STATICAT, VEHICLE_CONDITION_STATICAT);
    ITEM(CUP_O_Kornet_RUS_M_Summer, 10000, STATICAT, VEHICLE_CONDITION_STATICAT);
    ITEM(CUP_B_RBS70_ACR, 10000, STATICAT, VEHICLE_CONDITION_STATICAT);
    ITEM(CUP_B_TOW_TriPod_USMC, 10000, STATICAT, VEHICLE_CONDITION_STATICAT);

};