/*
    VEHICLE_TYPE = What type the vehicle is.
        types : ['AA', 'APC', 'ARMEDCAR', 'ARTILLERY', 'BOAT', 'HELI', 'PLANE', 'STATICAA', 'STATICAT', 'STATICMG', 'STATICMORTAR', 'TANK', 'UAV', 'UNARMEDCAR']

    VEHICLE_CONDITION = Condition to show.
        VEHICLE_CONDITION_X : VEHICLE_CONDITION + VEHICLE_TYPE

    VEHICLE_CONDITION_X can also be replaced with a string to add your own condition.

    ITEM(CLASSNAME, PRICE, VEHICLE_TYPE, VEHICLE_CONDITION_X);
*/

class argchi1980_vehicles_vanilla : vehicles_base
{
    ITEM(LIB_M1919_M2, 1000, STATICMG, VEHICLE_CONDITION_STATICMG);
    ITEM(I_G_HMG_02_F, 1500, STATICMG, VEHICLE_CONDITION_STATICMG);
    ITEM(I_G_HMG_02_high_F, 2000, STATICMG, VEHICLE_CONDITION_STATICMG);
    ITEM(tbd_spg, 5000, STATICAT, VEHICLE_CONDITION_STATICAT);
    ITEM(CLV_OERLIKON, 10000, STATICAA, VEHICLE_CONDITION_STATICAA);
    ITEM(CLV_OMM56, 40000, ARTILLERY, VEHICLE_CONDITION_ARTILLERY);

    ITEM(Unimog416_big, 1000, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);

    ITEM(acfaa_m113_m2, 35000, APC, VEHICLE_CONDITION_APC);

    ITEM(clv_Aml20, 25000, TANK, VEHICLE_CONDITION_TANK);
    ITEM(clv_AmlHS30, 30000, TANK, VEHICLE_CONDITION_TANK);
    ITEM(clv_Aml90, 40000, TANK, VEHICLE_CONDITION_TANK);
    ITEM(clv_Amx13, 60000, TANK, VEHICLE_CONDITION_TANK);
    ITEM(clv_Kurassier, 65000, TANK, VEHICLE_CONDITION_TANK);

    ITEM(pook_H13_transport, 20000, HELI, VEHICLE_CONDITION_HELI);
    ITEM(pook_H13_gunship, 27500, HELI, VEHICLE_CONDITION_HELI);
    ITEM(ACFAA_ARG_UH1D, 50000, HELI, VEHICLE_CONDITION_HELI);
    ITEM(ACFAA_ARG_UH1H_M60, 60000, HELI, VEHICLE_CONDITION_HELI);
};