//TO BE TOTALLY CHANGED (INCLUDE ION VICS)

/*
    VEHICLE_TYPE = What type the vehicle is.
        types : ['AA', 'APC', 'ARMEDCAR', 'ARTILLERY', 'BOAT', 'HELI', 'PLANE', 'STATICAA', 'STATICAT', 'STATICMG', 'STATICMORTAR', 'TANK', 'UAV', 'UNARMEDCAR']

    VEHICLE_CONDITION = Condition to show.
        VEHICLE_CONDITION_X : VEHICLE_CONDITION + VEHICLE_TYPE

    VEHICLE_CONDITION_X can also be replaced with a string to add your own condition.

    ITEM(CLASSNAME, PRICE, VEHICLE_TYPE, VEHICLE_CONDITION_X);
*/

class IONriv_vehicles_CUP : vehicles_base
{
    ITEM(CUP_I_SUV_ION, 400, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(I_G_Van_01_transport_F, 500, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(CUP_B_MTVR_BAF_WOOD, 600, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(CUP_I_nM1025_Unarmed_ION, 1000, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(CUP_I_FENNEK_ION, 1300, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(CUP_I_MATV_ION, 1500, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);

    ITEM(CUP_I_SUV_Armored_ION, 6000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_B_nM1025_SOV_M2_ION, 5000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_B_nM1025_SOV_Mk19_ION, 7000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_I_RG31_M2_GC_ION, 5000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_I_RG31_Mk19_ION, 8000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_I_FENNEK_HMG_ION, 10000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_I_FENNEK_GMG_ION, 15000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_I_MATV_HMG_ION, 11000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_I_MATV_GMG_ION, 16000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);

    ITEM(CUP_I_RG31E_M2_ION, 7000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_B_BAF_Coyote_GMG_W, 9000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_B_BAF_Coyote_L2A1_W, 5000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);

    ITEM(CUP_I_BTR80_ION, 10000, APC, VEHICLE_CONDITION_APC);
    ITEM(CUP_I_BTR80A_ION, 15000, APC, VEHICLE_CONDITION_APC);

    ITEM(CUP_B_FV510_GB_W, 20000, TANK, VEHICLE_CONDITION_TANK);
    ITEM(CUP_B_FV510_GB_W_SLAT, 21000, TANK, VEHICLE_CONDITION_TANK);

    ITEM(CUP_I_MH6M_ION, 15000, HELI, VEHICLE_CONDITION_HELI);
    ITEM(CUP_I_MH6M_ION_OBS, 20000, HELI, VEHICLE_CONDITION_HELI);

    ITEM(CUP_I_412_Mil_Transport_PMC, 12000, HELI, VEHICLE_CONDITION_HELI);
    ITEM(CUP_I_412_Mil_Utility_PMC, 11000, HELI, VEHICLE_CONDITION_HELI);
    ITEM(CUP_I_412_Military_Radar_PMC, 12500, HELI, VEHICLE_CONDITION_HELI);
    ITEM(CUP_I_412_Military_Armed_PMC, 21000, HELI, VEHICLE_CONDITION_HELI);
    ITEM(CUP_I_412_dynamicLoadout_PMC, 20500, HELI, VEHICLE_CONDITION_HELI);
    ITEM(CUP_I_412_Military_Armed_AT_PMC, 30000, HELI, VEHICLE_CONDITION_HELI);

    ITEM(CUP_I_CESSNA_T41_ARMED_ION, 10000, PLANE, VEHICLE_CONDITION_PLANE);

    ITEM(CUP_C_PBX_CIV, 500, BOAT, VEHICLE_CONDITION_BOAT);
    ITEM(CUP_C_Zodiac_CIV, 750, BOAT, VEHICLE_CONDITION_BOAT);
    ITEM(CUP_B_RHIB_USMC, 5000, BOAT, VEHICLE_CONDITION_BOAT);

    ITEM(I_G_HMG_02_F, 1000, STATICMG, VEHICLE_CONDITION_STATICMG);
    ITEM(I_G_HMG_02_high_F, 1000, STATICMG, VEHICLE_CONDITION_STATICMG);
    ITEM(CUP_B_MK19_TriPod_US, 1750, STATICMG, VEHICLE_CONDITION_STATICMG);

    ITEM(I_G_Mortar_01_F, 5000, STATICMORTAR, VEHICLE_CONDITION_STATICMORTAR);

    ITEM(CUP_B_CUP_Stinger_AA_pod_US, 6000, STATICAA, VEHICLE_CONDITION_STATICAA);

    ITEM(CUP_B_TOW_TriPod_USMC, 5000, STATICAT, VEHICLE_CONDITION_STATICAT);
};