/*
    VEHICLE_TYPE = What type the vehicle is.
        types : ['AA', 'APC', 'ARMEDCAR', 'ARTILLERY', 'BOAT', 'HELI', 'PLANE', 'STATICAA', 'STATICAT', 'STATICMG', 'STATICMORTAR', 'TANK', 'UAV', 'UNARMEDCAR']

    VEHICLE_CONDITION = Condition to show.
        VEHICLE_CONDITION_X : VEHICLE_CONDITION + VEHICLE_TYPE

    VEHICLE_CONDITION_X can also be replaced with a string to add your own condition.

    ITEM(CLASSNAME, PRICE, VEHICLE_TYPE, VEHICLE_CONDITION_X);
*/

class BLN_vehicles_CUP : vehicles_base
{
    ITEM(B_Quadbike_01_F, 100, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);

    ITEM(CUP_C_TT650_CIV, 50, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(CUP_C_Datsun_Plain, 200, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(CUP_C_Golf4_Sport_CR_Civ, 300, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(CUP_O_Hilux_unarmed_CR_CIV, 400, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(CUP_C_SUV_CIV, 400, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(CUP_C_Ural_Open_Civ_03, 500, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(CUP_B_Hilux_armored_unarmed_BLU_G_F, 700, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);

    ITEM(CUP_B_Hilux_AGS30_BLU_G_F, 4000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_B_Hilux_M2_BLU_G_F, 3000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_B_Hilux_SPG9_BLU_G_F, 5000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_B_Hilux_armored_AGS30_BLU_G_F, 5000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_B_Hilux_armored_M2_BLU_G_F, 4000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_B_Hilux_armored_SPG9_BLU_G_F, 6000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(CUP_B_Hilux_armored_metis_BLU_G_F, 10000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);

    ITEM(CUP_B_Hilux_zu23_BLU_G_F, 5000, AA, VEHICLE_CONDITION_AA);
    ITEM(CUP_B_Hilux_armored_zu23_BLU_G_F, 6000, AA, VEHICLE_CONDITION_AA);
    ITEM(CUP_B_Hilux_armored_igla_BLU_G_F, 14000, AA, VEHICLE_CONDITION_AA);
    ITEM(CUP_O_Ural_ZU23_SLA, 6000, AA, VEHICLE_CONDITION_AA);

    ITEM(CUP_B_Hilux_armored_BTR60_BLU_G_F, 10000, TANK, VEHICLE_CONDITION_TANK);
    ITEM(CUP_B_Hilux_armored_BMP1_BLU_G_F, 20000, TANK, VEHICLE_CONDITION_TANK);

    ITEM(CUP_B_Hilux_podnos_BLU_G_F, 9000, ARTILLERY, VEHICLE_CONDITION_ARTILLERY);
    ITEM(CUP_B_Hilux_armored_podnos_BLU_G_F, 10000, ARTILLERY, VEHICLE_CONDITION_ARTILLERY);
    ITEM(CUP_B_Hilux_armored_MLRS_BLU_G_F, 14000, ARTILLERY, VEHICLE_CONDITION_ARTILLERY);
    ITEM(CUP_B_Hilux_armored_UB32_BLU_G_F, 12000, ARTILLERY, VEHICLE_CONDITION_ARTILLERY);

    ITEM(I_C_Heli_Light_01_civil_F, 10000, HELI, VEHICLE_CONDITION_HELI);
    ITEM(CUP_C_412, 12000, HELI, VEHICLE_CONDITION_HELI);

    ITEM(CUP_I_CESSNA_T41_UNARMED_RACS, 8000, PLANE, VEHICLE_CONDITION_PLANE);
    ITEM(CUP_I_CESSNA_T41_ARMED_RACS, 12000, PLANE, VEHICLE_CONDITION_PLANE);

    ITEM(CUP_C_PBX_CIV, 500, BOAT, VEHICLE_CONDITION_BOAT);
    ITEM(CUP_C_Zodiac_CIV, 750, BOAT, VEHICLE_CONDITION_BOAT);

    ITEM(CUP_O_DSHKM_SLA, 500, STATICMG, VEHICLE_CONDITION_STATICMG);
    ITEM(I_G_HMG_02_F, 600, STATICMG, VEHICLE_CONDITION_STATICMG);
    ITEM(I_G_HMG_02_high_F, 600, STATICMG, VEHICLE_CONDITION_STATICMG);
    ITEM(CUP_I_AGS_TK_GUE, 600, STATICMG, VEHICLE_CONDITION_STATICMG);
    ITEM(CUP_O_KORD_high_RUS_M_Summer, 800, STATICMG, VEHICLE_CONDITION_STATICMG);

    ITEM(CUP_I_2b14_82mm_NAPA, 3000, STATICMORTAR, VEHICLE_CONDITION_STATICMORTAR);
    ITEM(I_G_Mortar_01_F, 5000, STATICMORTAR, VEHICLE_CONDITION_STATICMORTAR);

    ITEM(CUP_I_ZU23_NAPA, 4500, STATICAA, VEHICLE_CONDITION_STATICAA);

    ITEM(CUP_I_SPG9_NAPA, 4000, STATICAT, VEHICLE_CONDITION_STATICAT);

};