/*
    VEHICLE_TYPE = What type the vehicle is.
        types : ['AA', 'APC', 'ARMEDCAR', 'ARTILLERY', 'BOAT', 'HELI', 'PLANE', 'STATICAA', 
        'STATICAT', 'STATICMG', 'STATICMORTAR', 'TANK', 'UAV', 'UNARMEDCAR']

    VEHICLE_CONDITION = Condition to show.
        VEHICLE_CONDITION_X : VEHICLE_CONDITION + VEHICLE_TYPE

    VEHICLE_CONDITION_X can also be replaced with a string to add your own condition.

    ITEM(CLASSNAME, PRICE, VEHICLE_TYPE, VEHICLE_CONDITION_X);
*/

class vehicles_FAN : vehicles_base
{   
    // UNARMED CARS //
    ITEM("CUP_Wheeledvehicles_VWGolf", 2000, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM("A3_Soft_F_Offroad_01", 3000, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM("CUP_C_SUV_CIV", 2500, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM("C_Truck_02_covered_F", 3500, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM("CUP_I_Hilux_armored_unarmed_IND_G_F", 5000, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);

    ITEM("CUP_I_FENNEK_ION", 17500, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM("CUP_I_FENNEK_ION", 17500, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM("CUP_I_nM1025_Unarmed_DF_ION", 10000, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);

    // ARMED CARS //
    ITEM("CUP_I_Hilux_M2_IND_G_F", 5000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM("CUP_I_Hilux_AGS30_IND_G_F", 5000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM("CUP_I_Hilux_SPG9_IND_G_F", 6000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM("CUP_I_Hilux_armored_AGS30_IND_G_F", 6500, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM("CUP_I_Hilux_armored_M2_IND_G_F", 6500, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM("CUP_I_Hilux_armored_SPG9_IND_G_F", 10000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM("CUP_I_Hilux_armored_zu23_IND_G_F", 15000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM("CUP_I_Hilux_armored_igla_IND_G_F", 25000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM("CUP_I_Hilux_armored_metis_IND_G_F", 35000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM("CUP_I_Hilux_armored_BTR60_IND_G_F", 55000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM("CUP_I_Hilux_armored_BMP1_IND_G_F", 75000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);

    ITEM("CUP_I_nM1025_M240_ION", 12500, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM("CUP_I_nM1025_M2_ION", 15000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM("CUP_I_nM1025_Mk19_ION", 15000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);

    ITEM("CUP_B_nM1025_SOV_M2_ION", 20000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM("CUP_B_nM1025_SOV_Mk19_ION", 20000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM("CUP_I_nM1036_TOW_ION", 45000, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);

    ITEM("CUP_I_Hilux_armored_MLRS_IND_G_F", 50000, ARTILLERY, VEHICLE_CONDITION_ARTILLERY);
    ITEM("CUP_I_Hilux_armored_UB32_IND_G_F", 70000, ARTILLERY, VEHICLE_CONDITION_ARTILLERY);

    // APCS //
    ITEM("CUP_I_RG31E_M2_ION", 50000, APC, VEHICLE_CONDITION_APC);
    ITEM("CUP_I_BTR80_ION", 80000, APC, VEHICLE_CONDITION_APC);
    ITEM("CUP_I_BTR80A_ION", 90000, APC, VEHICLE_CONDITION_APC);

    // BOATS //
    ITEM("I_Boat_Transport_01_F", 3000, BOAT, VEHICLE_CONDITION_BOAT);
    ITEM("CUP_B_RHIB_USMC", 30000, BOAT, VEHICLE_CONDITION_BOAT);

    // HELIS //
    ITEM("CUP_I_MH6M_ION", 40000, HELI, VEHICLE_CONDITION_HELI);
    ITEM("CUP_C_412", 85000, HELI, VEHICLE_CONDITION_HELI);
    ITEM("CUP_I_412_Mil_Utility_PMC", 70000, HELI, VEHICLE_CONDITION_HELI);
    ITEM("CUP_I_412_Mil_Transport_PMC", 70000, HELI, VEHICLE_CONDITION_HELI);
    ITEM("CUP_I_412_dynamicLoadout_PMC", 90000, HELI, VEHICLE_CONDITION_HELI);
    ITEM("CUP_I_412_Military_Armed_PMC", 90000, HELI, VEHICLE_CONDITION_HELI);
    ITEM("CUP_I_412_Military_Armed_AT_PMC", 100000, HELI, VEHICLE_CONDITION_HELI);

    // PLANES //
    ITEM("CUP_C_CESSNA_CIV", 50000, PLANE, VEHICLE_CONDITION_PLANE);
    ITEM("CUP_I_CESSNA_T41_ARMED_ION", 50000, PLANE, VEHICLE_CONDITION_PLANE);

    // STATICS /
    ITEM("CUP_I_ZU23_NAPA", 10000, STATICAA, VEHICLE_CONDITION_STATICAA);
    ITEM("CUP_O_Igla_AA_pod_ChDKZ", 20000, STATICAA, VEHICLE_CONDITION_STATICAA);

    ITEM("CUP_I_SPG9_NAPA", 8500, STATICAT, VEHICLE_CONDITION_STATICAT);

    ITEM("I_G_HMG_02_F", 5000, STATICMG, VEHICLE_CONDITION_STATICMG);
    ITEM("I_G_HMG_02_high_F", 5000, STATICMG, VEHICLE_CONDITION_STATICMG);
    ITEM("CUP_I_AGS_UN", 5000, STATICMG, VEHICLE_CONDITION_STATICMG);
    ITEM("CUP_I_SearchLight_static_NAPA", 500, STATICMG, VEHICLE_CONDITION_STATICMG);

    ITEM("I_Mortar_01_F", 10000, STATICMORTAR, VEHICLE_CONDITION_STATICMORTAR);
    ITEM("CUP_I_2b14_82mm_NAPA", 5000, STATICMORTAR, VEHICLE_CONDITION_STATICMORTAR);

    // TANKS-IFVS //
    ITEM("CUP_I_T34_NAPA", 110000, TANK, VEHICLE_CONDITION_TANK);
    ITEM("CUP_I_BMP1_TK_GUE", 150000, TANK, VEHICLE_CONDITION_TANK);
};
